// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
@_spi(GoogleCloudInternal) public import GoogleLongRunning
@_spi(GoogleCloudInternal) public import GoogleWKT
@_spi(GoogleCloudInternal) public import GoogleGax

/// Service for creating and managing Data Fusion instances.
/// Data Fusion enables ETL developers to build code-free, data integration
/// pipelines via a point-and-click UI.
///
/// @Snippet(path: "DataFusionQuickstart")
public final class DataFusionClient: Clients.DataFusionProtocol, Sendable {
  let inner: any Clients.DataFusionStub
  let pollingErrorPolicy: GoogleGax.PollingErrorPolicy
  let pollingBackoffPolicy: GoogleGax.BackoffPolicy

  /// Creates a new `DataFusionClient` instance.
  public init(_ options: GoogleGax.ClientOptions = .init()) throws {
    var inner: any Clients.DataFusionStub = try Clients.DataFusionTransport(options)
    inner = Clients.DataFusionRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.DataFusionLogging(inner, logger: logger)
    }
    self.inner = inner
    self.pollingErrorPolicy = options.pollingErrorPolicy
    self.pollingBackoffPolicy = options.pollingBackoffPolicy
  }

  /// Lists possible versions for Data Fusion instances in the specified project
  /// and location.
  ///
  /// @Snippet(path: "DataFusion_ListAvailableVersions")
  public func listAvailableVersions(
    request: ListAvailableVersionsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudDataFusionV1.ListAvailableVersionsResponse {
    try await self.inner.listAvailableVersions(request: request, options: options)
  }

  /// Lists Data Fusion instances in the specified project and location.
  ///
  /// @Snippet(path: "DataFusion_ListInstances")
  public func listInstances(
    request: ListInstancesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudDataFusionV1.ListInstancesResponse {
    try await self.inner.listInstances(request: request, options: options)
  }

  /// Gets details of a single Data Fusion instance.
  ///
  /// @Snippet(path: "DataFusion_GetInstance")
  public func getInstance(
    request: GetInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudDataFusionV1.Instance {
    try await self.inner.getInstance(request: request, options: options)
  }

  /// Creates a new Data Fusion instance in the specified project and location.
  ///
  /// @Snippet(path: "DataFusion_CreateInstance")
  public func createInstance(
    request: CreateInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createInstance(request: request, options: options)
  }

  /// Creates a new Data Fusion instance in the specified project and location.
  ///
  /// @Snippet(path: "DataFusion_CreateInstance")
  public func createInstancePollingUntilDone(
    request: CreateInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Instance> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Instance>.State
      in
      return try op._extractStatus(Instance.self)
    }
    let rawOp = try await self.createInstance(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Instance>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Deletes a single Date Fusion instance.
  ///
  /// @Snippet(path: "DataFusion_DeleteInstance")
  public func deleteInstance(
    request: DeleteInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteInstance(request: request, options: options)
  }

  /// Deletes a single Date Fusion instance.
  ///
  /// @Snippet(path: "DataFusion_DeleteInstance")
  public func deleteInstancePollingUntilDone(
    request: DeleteInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State
      in
      return try op._extractStatusEmpty()
    }
    let rawOp = try await self.deleteInstance(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Updates a single Data Fusion instance.
  ///
  /// @Snippet(path: "DataFusion_UpdateInstance")
  public func updateInstance(
    request: UpdateInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.updateInstance(request: request, options: options)
  }

  /// Updates a single Data Fusion instance.
  ///
  /// @Snippet(path: "DataFusion_UpdateInstance")
  public func updateInstancePollingUntilDone(
    request: UpdateInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Instance> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Instance>.State
      in
      return try op._extractStatus(Instance.self)
    }
    let rawOp = try await self.updateInstance(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Instance>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Restart a single Data Fusion instance.
  /// At the end of an operation instance is fully restarted.
  ///
  /// @Snippet(path: "DataFusion_RestartInstance")
  public func restartInstance(
    request: RestartInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.restartInstance(request: request, options: options)
  }

  /// Restart a single Data Fusion instance.
  /// At the end of an operation instance is fully restarted.
  ///
  /// @Snippet(path: "DataFusion_RestartInstance")
  public func restartInstancePollingUntilDone(
    request: RestartInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Instance> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Instance>.State
      in
      return try op._extractStatus(Instance.self)
    }
    let rawOp = try await self.restartInstance(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Instance>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "DataFusion_ListOperations")
  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    try await self.inner.listOperations(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "DataFusion_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "DataFusion_DeleteOperation")
  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.deleteOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "DataFusion_CancelOperation")
  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.cancelOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `DataFusionClient`.
  ///
  /// To mock `DataFusionClient` change your functions to receive
  /// `some DataFusionProtocol` or `any DataFusionProtocol`
  /// and pass a mock implementation in your tests.
  public protocol DataFusionProtocol: Sendable {
    /// See `DataFusionClient.createInstance`.
    func createInstancePollingUntilDone(request: CreateInstanceRequest) async throws
      -> any GoogleGax.PollableOperation<Instance>

    /// See `DataFusionClient.createInstance`.
    func createInstancePollingUntilDone(
      parent: Swift.String,
      instance: Instance?,
      instanceId: Swift.String,
    ) async throws -> any GoogleGax.PollableOperation<Instance>

    /// See `DataFusionClient.deleteInstance`.
    func deleteInstancePollingUntilDone(request: DeleteInstanceRequest) async throws
      -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `DataFusionClient.deleteInstance`.
    func deleteInstancePollingUntilDone(
      name: Swift.String,
    ) async throws -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `DataFusionClient.updateInstance`.
    func updateInstancePollingUntilDone(request: UpdateInstanceRequest) async throws
      -> any GoogleGax.PollableOperation<Instance>

    /// See `DataFusionClient.updateInstance`.
    func updateInstancePollingUntilDone(
      instance: Instance?,
      updateMask: GoogleWKT.WKTFieldMask?,
    ) async throws -> any GoogleGax.PollableOperation<Instance>

    /// See `DataFusionClient.restartInstance`.
    func restartInstancePollingUntilDone(request: RestartInstanceRequest) async throws
      -> any GoogleGax.PollableOperation<Instance>

    /// See `DataFusionClient.listAvailableVersions`.
    func listAvailableVersions(
      request: ListAvailableVersionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDataFusionV1.ListAvailableVersionsResponse

    /// See `DataFusionClient.listInstances`.
    func listInstances(
      request: ListInstancesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDataFusionV1.ListInstancesResponse

    /// See `DataFusionClient.getInstance`.
    func getInstance(
      request: GetInstanceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDataFusionV1.Instance

    /// See `DataFusionClient.createInstance`.
    func createInstance(
      request: CreateInstanceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `DataFusionClient.createInstance`.
    func createInstancePollingUntilDone(
      request: CreateInstanceRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Instance>

    /// See `DataFusionClient.deleteInstance`.
    func deleteInstance(
      request: DeleteInstanceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `DataFusionClient.deleteInstance`.
    func deleteInstancePollingUntilDone(
      request: DeleteInstanceRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `DataFusionClient.updateInstance`.
    func updateInstance(
      request: UpdateInstanceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `DataFusionClient.updateInstance`.
    func updateInstancePollingUntilDone(
      request: UpdateInstanceRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Instance>

    /// See `DataFusionClient.restartInstance`.
    func restartInstance(
      request: RestartInstanceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `DataFusionClient.restartInstance`.
    func restartInstancePollingUntilDone(
      request: RestartInstanceRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Instance>

    /// See `DataFusionClient.listOperations`.
    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    /// See `DataFusionClient.deleteOperation`.
    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws

    /// See `DataFusionClient.cancelOperation`.
    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws
  }
}

// Default implementations
extension Clients.DataFusionProtocol {
  public func listAvailableVersions(request: ListAvailableVersionsRequest) async throws
    -> GoogleCloudDataFusionV1.ListAvailableVersionsResponse
  {
    try await self.listAvailableVersions(request: request, options: .init())
  }

  public func listAvailableVersions(
    request: ListAvailableVersionsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudDataFusionV1.ListAvailableVersionsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listAvailableVersions(
    byItem: ListAvailableVersionsRequest
  ) -> any AsyncSequence<Version, Swift.Error> {
    self.listAvailableVersions(byItem: byItem, options: .init())
  }

  /// Lists possible versions for Data Fusion instances in the specified project
  /// and location.
  ///
  /// @Snippet(path: "DataFusion_ListAvailableVersions")
  public func listAvailableVersions(
    byItem: ListAvailableVersionsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<Version, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudDataFusionV1.ListAvailableVersionsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listAvailableVersions(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listAvailableVersions(
    parent: Swift.String,
  ) -> any AsyncSequence<Version, Swift.Error> {
    let request = ListAvailableVersionsRequest().with {
      $0.parent = parent
    }
    return self.listAvailableVersions(byItem: request)
  }

  public func listInstances(request: ListInstancesRequest) async throws
    -> GoogleCloudDataFusionV1.ListInstancesResponse
  {
    try await self.listInstances(request: request, options: .init())
  }

  public func listInstances(
    request: ListInstancesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudDataFusionV1.ListInstancesResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listInstances(
    byItem: ListInstancesRequest
  ) -> any AsyncSequence<Instance, Swift.Error> {
    self.listInstances(byItem: byItem, options: .init())
  }

  /// Lists Data Fusion instances in the specified project and location.
  ///
  /// @Snippet(path: "DataFusion_ListInstances")
  public func listInstances(
    byItem: ListInstancesRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<Instance, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudDataFusionV1.ListInstancesResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listInstances(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func getInstance(request: GetInstanceRequest) async throws
    -> GoogleCloudDataFusionV1.Instance
  {
    try await self.getInstance(request: request, options: .init())
  }

  public func getInstance(
    request: GetInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudDataFusionV1.Instance {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createInstance(request: CreateInstanceRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.createInstance(request: request, options: .init())
  }

  public func createInstance(
    request: CreateInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createInstancePollingUntilDone(request: CreateInstanceRequest) async throws
    -> any GoogleGax.PollableOperation<Instance>
  {
    try await self.createInstancePollingUntilDone(request: request, options: .init())
  }

  public func createInstancePollingUntilDone(
    request: CreateInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Instance> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Instance>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createInstancePollingUntilDone(
    parent: Swift.String,
    instance: Instance?,
    instanceId: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<Instance> {
    let request = CreateInstanceRequest().with {
      $0.parent = parent
      $0.instance = instance
      $0.instanceId = instanceId
    }
    return try await self.createInstancePollingUntilDone(request: request)
  }

  public func deleteInstance(request: DeleteInstanceRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.deleteInstance(request: request, options: .init())
  }

  public func deleteInstance(
    request: DeleteInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteInstancePollingUntilDone(request: DeleteInstanceRequest) async throws
    -> any GoogleGax.PollableOperation<Swift.Void>
  {
    try await self.deleteInstancePollingUntilDone(request: request, options: .init())
  }

  public func deleteInstancePollingUntilDone(
    request: DeleteInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteInstancePollingUntilDone(
    name: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let request = DeleteInstanceRequest().with {
      $0.name = name
    }
    return try await self.deleteInstancePollingUntilDone(request: request)
  }

  public func updateInstance(request: UpdateInstanceRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.updateInstance(request: request, options: .init())
  }

  public func updateInstance(
    request: UpdateInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateInstancePollingUntilDone(request: UpdateInstanceRequest) async throws
    -> any GoogleGax.PollableOperation<Instance>
  {
    try await self.updateInstancePollingUntilDone(request: request, options: .init())
  }

  public func updateInstancePollingUntilDone(
    request: UpdateInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Instance> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Instance>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func updateInstancePollingUntilDone(
    instance: Instance?,
    updateMask: GoogleWKT.WKTFieldMask?,
  ) async throws -> any GoogleGax.PollableOperation<Instance> {
    let request = UpdateInstanceRequest().with {
      $0.instance = instance
      $0.updateMask = updateMask
    }
    return try await self.updateInstancePollingUntilDone(request: request)
  }

  public func restartInstance(request: RestartInstanceRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.restartInstance(request: request, options: .init())
  }

  public func restartInstance(
    request: RestartInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func restartInstancePollingUntilDone(request: RestartInstanceRequest) async throws
    -> any GoogleGax.PollableOperation<Instance>
  {
    try await self.restartInstancePollingUntilDone(request: request, options: .init())
  }

  public func restartInstancePollingUntilDone(
    request: RestartInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Instance> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Instance>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
    -> GoogleLongRunning.ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest
  ) -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    self.listOperations(byItem: byItem, options: .init())
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "DataFusion_ListOperations")
  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listOperations(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listOperations(
    name: Swift.String,
    filter: Swift.String,
  ) -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let request = GoogleLongRunning.ListOperationsRequest().with {
      $0.name = name
      $0.filter = filter
    }
    return self.listOperations(byItem: request)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }

  public func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws {
    try await self.deleteOperation(request: request, options: .init())
  }

  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.DeleteOperationRequest().with {
      $0.name = name
    }
    try await self.deleteOperation(request: request)
  }

  public func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws {
    try await self.cancelOperation(request: request, options: .init())
  }

  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func cancelOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.CancelOperationRequest().with {
      $0.name = name
    }
    try await self.cancelOperation(request: request)
  }
}
