// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// Represents a Data Fusion instance.
public struct Instance: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. The name of this instance is in the form of
  /// projects/{project}/locations/{location}/instances/{instance}.
  public var name: Swift.String = Swift.String()

  /// A description of this instance.
  public var description: Swift.String = Swift.String()

  /// Required. Instance type.
  public var type: Instance.Type_ = Instance.Type_()

  /// Option to enable Stackdriver Logging.
  public var enableStackdriverLogging: Swift.Bool = Swift.Bool()

  /// Option to enable Stackdriver Monitoring.
  public var enableStackdriverMonitoring: Swift.Bool = Swift.Bool()

  /// Specifies whether the Data Fusion instance should be private. If set to
  /// true, all Data Fusion nodes will have private IP addresses and will not be
  /// able to access the public internet.
  public var privateInstance: Swift.Bool = Swift.Bool()

  /// Network configuration options. These are required when a private Data
  /// Fusion instance is to be created.
  public var networkConfig: NetworkConfig? = nil

  /// The resource labels for instance to use to annotate any related underlying
  /// resources such as Compute Engine VMs. The character '=' is not allowed to
  /// be used within the labels.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Map of additional options used to configure the behavior of
  /// Data Fusion instance.
  public var options: [Swift.String: Swift.String] = [:]

  /// Output only. The time the instance was created.
  public var createTime: GoogleWKT.Timestamp? = nil

  /// Output only. The time the instance was last updated.
  public var updateTime: GoogleWKT.Timestamp? = nil

  /// Output only. The current state of this Data Fusion instance.
  public var state: Instance.State = Instance.State()

  /// Output only. Additional information about the current state of this Data
  /// Fusion instance if available.
  public var stateMessage: Swift.String = Swift.String()

  /// Output only. Endpoint on which the Data Fusion UI is accessible.
  public var serviceEndpoint: Swift.String = Swift.String()

  /// Name of the zone in which the Data Fusion instance will be created. Only
  /// DEVELOPER instances use this field.
  public var zone: Swift.String = Swift.String()

  /// Current version of the Data Fusion. Only specifiable in Update.
  public var version: Swift.String = Swift.String()

  /// Output only. Deprecated. Use tenant_project_id instead to extract the tenant project ID.
  @available(*, deprecated)
  public var serviceAccount: Swift.String = Swift.String()

  /// Display name for an instance.
  public var displayName: Swift.String = Swift.String()

  /// Available versions that the instance can be upgraded to using
  /// UpdateInstanceRequest.
  public var availableVersion: [Version] = []

  /// Output only. Endpoint on which the REST APIs is accessible.
  public var apiEndpoint: Swift.String = Swift.String()

  /// Output only. Cloud Storage bucket generated by Data Fusion in the customer project.
  public var gcsBucket: Swift.String = Swift.String()

  /// List of accelerators enabled for this CDF instance.
  public var accelerators: [Accelerator] = []

  /// Output only. P4 service account for the customer project.
  public var p4ServiceAccount: Swift.String = Swift.String()

  /// Output only. The name of the tenant project.
  public var tenantProjectId: Swift.String = Swift.String()

  /// User-managed service account to set on Dataproc when Cloud Data Fusion
  /// creates Dataproc to run data processing pipelines.
  ///
  /// This allows users to have fine-grained access control on Dataproc's
  /// accesses to cloud resources.
  public var dataprocServiceAccount: Swift.String = Swift.String()

  /// Option to enable granular role-based access control.
  public var enableRbac: Swift.Bool = Swift.Bool()

  /// The crypto key configuration. This field is used by the Customer-Managed
  /// Encryption Keys (CMEK) feature.
  public var cryptoKeyConfig: CryptoKeyConfig? = nil

  /// Output only. If the instance state is DISABLED, the reason for disabling the instance.
  public var disabledReason: [Instance.DisabledReason] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Instance`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Instance().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let description = CodingKeys(stringValue: "description")
    static let type = CodingKeys(stringValue: "type")
    static let enableStackdriverLogging = CodingKeys(stringValue: "enableStackdriverLogging")
    static let enableStackdriverMonitoring = CodingKeys(stringValue: "enableStackdriverMonitoring")
    static let privateInstance = CodingKeys(stringValue: "privateInstance")
    static let networkConfig = CodingKeys(stringValue: "networkConfig")
    static let labels = CodingKeys(stringValue: "labels")
    static let options = CodingKeys(stringValue: "options")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let state = CodingKeys(stringValue: "state")
    static let stateMessage = CodingKeys(stringValue: "stateMessage")
    static let serviceEndpoint = CodingKeys(stringValue: "serviceEndpoint")
    static let zone = CodingKeys(stringValue: "zone")
    static let version = CodingKeys(stringValue: "version")
    static let serviceAccount = CodingKeys(stringValue: "serviceAccount")
    static let displayName = CodingKeys(stringValue: "displayName")
    static let availableVersion = CodingKeys(stringValue: "availableVersion")
    static let apiEndpoint = CodingKeys(stringValue: "apiEndpoint")
    static let gcsBucket = CodingKeys(stringValue: "gcsBucket")
    static let accelerators = CodingKeys(stringValue: "accelerators")
    static let p4ServiceAccount = CodingKeys(stringValue: "p4ServiceAccount")
    static let tenantProjectId = CodingKeys(stringValue: "tenantProjectId")
    static let dataprocServiceAccount = CodingKeys(stringValue: "dataprocServiceAccount")
    static let enableRbac = CodingKeys(stringValue: "enableRbac")
    static let cryptoKeyConfig = CodingKeys(stringValue: "cryptoKeyConfig")
    static let disabledReason = CodingKeys(stringValue: "disabledReason")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "description",
      "type",
      "enableStackdriverLogging",
      "enableStackdriverMonitoring",
      "privateInstance",
      "networkConfig",
      "labels",
      "options",
      "createTime",
      "updateTime",
      "state",
      "stateMessage",
      "serviceEndpoint",
      "zone",
      "version",
      "serviceAccount",
      "displayName",
      "availableVersion",
      "apiEndpoint",
      "gcsBucket",
      "accelerators",
      "p4ServiceAccount",
      "tenantProjectId",
      "dataprocServiceAccount",
      "enableRbac",
      "cryptoKeyConfig",
      "disabledReason",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
      self.description = value
    }
    if let value = try container.decodeIfPresent(Instance.Type_.self, forKey: .type) {
      self.type = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .enableStackdriverLogging)
    {
      self.enableStackdriverLogging = value
    }
    if let value = try container.decodeIfPresent(
      Swift.Bool.self, forKey: .enableStackdriverMonitoring)
    {
      self.enableStackdriverMonitoring = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .privateInstance) {
      self.privateInstance = value
    }
    self.networkConfig = try container.decodeIfPresent(NetworkConfig.self, forKey: .networkConfig)
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .labels)
    {
      self.labels = value
    }
    if let value = try container.decodeIfPresent(
      [Swift.String: Swift.String].self, forKey: .options)
    {
      self.options = value
    }
    self.createTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .updateTime)
    if let value = try container.decodeIfPresent(Instance.State.self, forKey: .state) {
      self.state = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .stateMessage) {
      self.stateMessage = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .serviceEndpoint) {
      self.serviceEndpoint = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .zone) {
      self.zone = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .version) {
      self.version = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .serviceAccount) {
      self.serviceAccount = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .displayName) {
      self.displayName = value
    }
    if let value = try container.decodeIfPresent([Version].self, forKey: .availableVersion) {
      self.availableVersion = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .apiEndpoint) {
      self.apiEndpoint = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .gcsBucket) {
      self.gcsBucket = value
    }
    if let value = try container.decodeIfPresent([Accelerator].self, forKey: .accelerators) {
      self.accelerators = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .p4ServiceAccount) {
      self.p4ServiceAccount = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .tenantProjectId) {
      self.tenantProjectId = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .dataprocServiceAccount)
    {
      self.dataprocServiceAccount = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .enableRbac) {
      self.enableRbac = value
    }
    self.cryptoKeyConfig = try container.decodeIfPresent(
      CryptoKeyConfig.self, forKey: .cryptoKeyConfig)
    if let value = try container.decodeIfPresent(
      [Instance.DisabledReason].self, forKey: .disabledReason)
    {
      self.disabledReason = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.description, forKey: .description)
    try container.encode(self.type, forKey: .type)
    try container.encode(self.enableStackdriverLogging, forKey: .enableStackdriverLogging)
    try container.encode(self.enableStackdriverMonitoring, forKey: .enableStackdriverMonitoring)
    try container.encode(self.privateInstance, forKey: .privateInstance)
    try container.encodeIfPresent(self.networkConfig, forKey: .networkConfig)
    try container.encode(self.labels, forKey: .labels)
    try container.encode(self.options, forKey: .options)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encode(self.state, forKey: .state)
    try container.encode(self.stateMessage, forKey: .stateMessage)
    try container.encode(self.serviceEndpoint, forKey: .serviceEndpoint)
    try container.encode(self.zone, forKey: .zone)
    try container.encode(self.version, forKey: .version)
    try container.encode(self.serviceAccount, forKey: .serviceAccount)
    try container.encode(self.displayName, forKey: .displayName)
    try container.encode(self.availableVersion, forKey: .availableVersion)
    try container.encode(self.apiEndpoint, forKey: .apiEndpoint)
    try container.encode(self.gcsBucket, forKey: .gcsBucket)
    try container.encode(self.accelerators, forKey: .accelerators)
    try container.encode(self.p4ServiceAccount, forKey: .p4ServiceAccount)
    try container.encode(self.tenantProjectId, forKey: .tenantProjectId)
    try container.encode(self.dataprocServiceAccount, forKey: .dataprocServiceAccount)
    try container.encode(self.enableRbac, forKey: .enableRbac)
    try container.encodeIfPresent(self.cryptoKeyConfig, forKey: .cryptoKeyConfig)
    try container.encode(self.disabledReason, forKey: .disabledReason)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Represents the type of Data Fusion instance. Each type is configured with
  /// the default settings for processing and memory.
  public enum Type_: Codable, Equatable, Sendable {
    /// No type specified. The instance creation will fail.
    case unspecified
    /// Basic Data Fusion instance. In Basic type, the user will be able to
    /// create data pipelines using point and click UI. However, there are
    /// certain limitations, such as fewer number of concurrent pipelines, no
    /// support for streaming pipelines, etc.
    case basic
    /// Enterprise Data Fusion instance. In Enterprise type, the user will have
    /// all features available, such as support for streaming pipelines, higher
    /// number of concurrent pipelines, etc.
    case enterprise
    /// Developer Data Fusion instance. In Developer type, the user will have all
    /// features available but with restrictive capabilities. This is to help
    /// enterprises design and develop their data ingestion and integration
    /// pipelines at low cost.
    case developer
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .basic: return 1
      case .enterprise: return 2
      case .developer: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "TYPE_UNSPECIFIED"
      case .basic: return "BASIC"
      case .enterprise: return "ENTERPRISE"
      case .developer: return "DEVELOPER"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Type_/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "TYPE_UNSPECIFIED": self = .unspecified
      case "BASIC": self = .basic
      case "ENTERPRISE": self = .enterprise
      case "DEVELOPER": self = .developer
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Type_/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .basic
      case 2: self = .enterprise
      case 3: self = .developer
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("TYPE_UNSPECIFIED")
      case .basic: return try container.encode("BASIC")
      case .enterprise: return try container.encode("ENTERPRISE")
      case .developer: return try container.encode("DEVELOPER")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Represents the state of a Data Fusion instance
  public enum State: Codable, Equatable, Sendable {
    /// Instance does not have a state yet
    case unspecified
    /// Instance is being created
    case creating
    /// Instance is active and ready for requests. This corresponds to 'RUNNING'
    /// in datafusion.v1beta1.
    case active
    /// Instance creation failed
    case failed
    /// Instance is being deleted
    case deleting
    /// Instance is being upgraded
    case upgrading
    /// Instance is being restarted
    case restarting
    /// Instance is being updated on customer request
    case updating
    /// Instance is being auto-updated
    case autoUpdating
    /// Instance is being auto-upgraded
    case autoUpgrading
    /// Instance is disabled
    case disabled
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .creating: return 1
      case .active: return 2
      case .failed: return 3
      case .deleting: return 4
      case .upgrading: return 5
      case .restarting: return 6
      case .updating: return 7
      case .autoUpdating: return 8
      case .autoUpgrading: return 9
      case .disabled: return 10
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .creating: return "CREATING"
      case .active: return "ACTIVE"
      case .failed: return "FAILED"
      case .deleting: return "DELETING"
      case .upgrading: return "UPGRADING"
      case .restarting: return "RESTARTING"
      case .updating: return "UPDATING"
      case .autoUpdating: return "AUTO_UPDATING"
      case .autoUpgrading: return "AUTO_UPGRADING"
      case .disabled: return "DISABLED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "CREATING": self = .creating
      case "ACTIVE": self = .active
      case "FAILED": self = .failed
      case "DELETING": self = .deleting
      case "UPGRADING": self = .upgrading
      case "RESTARTING": self = .restarting
      case "UPDATING": self = .updating
      case "AUTO_UPDATING": self = .autoUpdating
      case "AUTO_UPGRADING": self = .autoUpgrading
      case "DISABLED": self = .disabled
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .creating
      case 2: self = .active
      case 3: self = .failed
      case 4: self = .deleting
      case 5: self = .upgrading
      case 6: self = .restarting
      case 7: self = .updating
      case 8: self = .autoUpdating
      case 9: self = .autoUpgrading
      case 10: self = .disabled
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("STATE_UNSPECIFIED")
      case .creating: return try container.encode("CREATING")
      case .active: return try container.encode("ACTIVE")
      case .failed: return try container.encode("FAILED")
      case .deleting: return try container.encode("DELETING")
      case .upgrading: return try container.encode("UPGRADING")
      case .restarting: return try container.encode("RESTARTING")
      case .updating: return try container.encode("UPDATING")
      case .autoUpdating: return try container.encode("AUTO_UPDATING")
      case .autoUpgrading: return try container.encode("AUTO_UPGRADING")
      case .disabled: return try container.encode("DISABLED")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The reason for disabling the instance if the state is DISABLED.
  public enum DisabledReason: Codable, Equatable, Sendable {
    /// This is an unknown reason for disabling.
    case unspecified
    /// The KMS key used by the instance is either revoked or denied access to
    case kmsKeyIssue
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .kmsKeyIssue: return 1
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "DISABLED_REASON_UNSPECIFIED"
      case .kmsKeyIssue: return "KMS_KEY_ISSUE"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:DisabledReason/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "DISABLED_REASON_UNSPECIFIED": self = .unspecified
      case "KMS_KEY_ISSUE": self = .kmsKeyIssue
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:DisabledReason/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .kmsKeyIssue
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("DISABLED_REASON_UNSPECIFIED")
      case .kmsKeyIssue: return try container.encode("KMS_KEY_ISSUE")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.datafusion.v1.Instance"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
