// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Request message for the list available versions request.
public struct ListAvailableVersionsRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The project and location for which to retrieve instance information
  /// in the format projects/{project}/locations/{location}.
  public var parent: Swift.String = Swift.String()

  /// The maximum number of items to return.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// The next_page_token value to use if there are additional
  /// results to retrieve for this list request.
  public var pageToken: Swift.String = Swift.String()

  /// Whether or not to return the latest patch of every available minor version.
  /// If true, only the latest patch will be returned. Ex. if allowed versions is
  /// [6.1.1, 6.1.2, 6.2.0] then response will be [6.1.2, 6.2.0]
  public var latestPatchOnly: Swift.Bool = Swift.Bool()

  /// Initialize a new instance of `ListAvailableVersionsRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListAvailableVersionsRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.datafusion.v1.ListAvailableVersionsRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
